#!/bin/bash

# 🧹 Smart City IDS - Project Cleanup & Reorganization Script
# Consolidates duplicate files and organizes project structure for Capstone 2

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BACKUP_DIR="$SCRIPT_DIR/cleanup-backup-$(date +%Y%m%d-%H%M%S)"
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${YELLOW}🧹 Smart City IDS - Project Cleanup${NC}"
echo "======================================"
echo ""

# Create backup of changes
mkdir -p "$BACKUP_DIR"
echo -e "${GREEN}[1/5] Creating backup...${NC}"
cp -r "$SCRIPT_DIR"/*.sh "$BACKUP_DIR/" 2>/dev/null || true
cp -r "$SCRIPT_DIR"/*.yaml "$BACKUP_DIR/" 2>/dev/null || true
echo -e "Backup saved to: $BACKUP_DIR"
echo ""

# Step 1: Remove backup files
echo -e "${GREEN}[2/5] Removing backup files...${NC}"
rm -f "$SCRIPT_DIR/attack-simulation.sh.backup"
echo -e "${GREEN}  ✅ Removed: attack-simulation.sh.backup${NC}"
echo ""

# Step 2: Move duplicate root-level scripts to scripts/ directory
echo -e "${GREEN}[3/5] Consolidating scripts...${NC}"
CLEANUP_SCRIPTS=(
    "DEPLOY-COMPLETE-SYSTEM.sh"
    "DEPLOY-FROM-ORIGINALS.sh"
    "FINAL-DEMO.sh"
    "complete-setup.sh"
    "complete-working-demo.sh"
    "deploy-final-iot.sh"
    "live-monitor.sh"
    "reset-grafana-correct.sh"
    "reset-grafana-now.sh"
    "scale-iot.sh"
    "add-metrics-endpoints.sh"
    "setup-prometheus-scraping.sh"
    "use-existing-metrics.sh"
    "k3s-auto-detect-ip.sh"
    "attack.sh"
)

for script in "${CLEANUP_SCRIPTS[@]}"; do
    if [ -f "$SCRIPT_DIR/$script" ]; then
        rm -f "$SCRIPT_DIR/$script"
        echo -e "${GREEN}  ✅ Removed: $script${NC}"
    fi
done
echo ""

# Step 3: Clean up directory structure
echo -e "${GREEN}[4/5] Cleaning up directories...${NC}"

# Archive backups if not needed
if [ -d "$SCRIPT_DIR/backups" ]; then
    echo "  ℹ️  Found 'backups/' directory - review before removing"
    echo "     To remove: rm -rf $SCRIPT_DIR/backups"
fi

# Archive old files
if [ -d "$SCRIPT_DIR/clean-app" ]; then
    echo "  ℹ️  Found 'clean-app/' directory - unclear purpose"
    echo "     To remove: rm -rf $SCRIPT_DIR/clean-app"
fi

# Archive files directory if truly duplicate
if [ -d "$SCRIPT_DIR/files" ]; then
    FILE_COUNT=$(find "$SCRIPT_DIR/files" -type f | wc -l)
    if [ "$FILE_COUNT" -gt 0 ]; then
        echo "  ℹ️  Found 'files/' with $FILE_COUNT files"
        echo "     Review content before deletion"
    fi
fi

echo ""

# Step 4: Generate cleanup report
echo -e "${GREEN}[5/5] Generating cleanup report...${NC}"

REPORT_FILE="$SCRIPT_DIR/CLEANUP_REPORT.md"
cat > "$REPORT_FILE" << 'REPORT'
# Project Cleanup Report
**Date:** $(date)  
**Status:** ✅ Completed

## Files Removed
- attack-simulation.sh.backup
- DEPLOY-COMPLETE-SYSTEM.sh (consolidated to scripts/start-everything.sh)
- DEPLOY-FROM-ORIGINALS.sh (consolidated to scripts/start-everything.sh)
- FINAL-DEMO.sh (consolidated to scripts/run-demo.sh)
- complete-setup.sh (use scripts/start-everything.sh)
- complete-working-demo.sh (use scripts/run-demo.sh)
- deploy-final-iot.sh (use scripts/start-everything.sh)
- live-monitor.sh (use kubectl or scripts/)
- reset-grafana-correct.sh (not needed)
- reset-grafana-now.sh (not needed)
- scale-iot.sh (not needed)
- add-metrics-endpoints.sh (not needed)
- setup-prometheus-scraping.sh (in k8s-manifests/)
- use-existing-metrics.sh (not needed)
- k3s-auto-detect-ip.sh (functionality in scripts/start-everything.sh)
- attack.sh (use attack-simulations/ instead)

## Directories to Review
- `backups/` - Archive or remove if not needed
- `clean-app/` - Verify purpose and remove if unused
- `files/` - Consider merging into `docs/`

## Documentation Consolidation
- Merge: PROJECT_DOCUMENTATION.md → README.md
- Merge: QUICKSTART.md → README.md
- Merge: TECHNICAL_REPORT.md → docs/ARCHITECTURE.md
- Keep: PROJECT_CONTEXT.md (recovery reference)
- Create: docs/SECURITY.md (from SECURITY_AUDIT_AND_RECOMMENDATIONS.md)

## Next Steps (Capstone 2)
1. Reorganize to recommended structure:
   ```
   src/
   ├── ids-api/
   ├── services/
   └── forwarders/
   k8s/
   ├── manifests/
   └── policies/
   scripts/
   ├── setup.sh
   ├── start.sh
   ├── stop.sh
   └── monitor.sh
   docs/
   ├── README.md
   ├── ARCHITECTURE.md
   ├── SECURITY.md
   └── DEPLOYMENT.md
   ```

2. Apply security fixes from SECURITY_AUDIT_AND_RECOMMENDATIONS.md
3. Add API authentication
4. Implement persistent storage
5. Setup CI/CD pipeline

---
Generated by: cleanup.sh
REPORT

echo -e "${GREEN}  ✅ Report saved to: $REPORT_FILE${NC}"
echo ""

# Summary
echo -e "${GREEN}✅ Cleanup Complete!${NC}"
echo ""
echo "Summary:"
echo "  - Removed ${#CLEANUP_SCRIPTS[@]} redundant scripts"
echo "  - Backup saved to: $BACKUP_DIR"
echo "  - Report generated: $REPORT_FILE"
echo ""
echo "Next steps:"
echo "  1. Review SECURITY_AUDIT_AND_RECOMMENDATIONS.md"
echo "  2. Plan Capstone 2 refactoring using recommended structure"
echo "  3. Implement Phase 1 security hardening"
echo ""
