#!/usr/bin/env bash
# generate-grafana-provisioning.sh
#
# Reads Grafana dashboard JSON files from infrastructure/monitoring/
# and writes a single Kubernetes ConfigMap manifest that Grafana
# auto-provisions on startup.
#
# Output: k8s-manifests/grafana-provisioning-dashboards.yaml
#
# Usage:
#   bash scripts/generate-grafana-provisioning.sh
#   kubectl apply -f k8s-manifests/grafana-provisioning-dashboards.yaml -n monitoring

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

DASHBOARD_DIR="$PROJECT_ROOT/infrastructure/monitoring"
OUTPUT="$PROJECT_ROOT/k8s-manifests/grafana-provisioning-dashboards.yaml"
NAMESPACE="monitoring"

# ── Collect dashboard JSON files ─────────────────────────────────
json_files=()
for f in "$DASHBOARD_DIR"/*.json; do
  [[ -f "$f" ]] || continue
  json_files+=("$f")
done

if [[ ${#json_files[@]} -eq 0 ]]; then
  echo "ERROR: No .json files found in $DASHBOARD_DIR" >&2
  exit 1
fi

echo "Found ${#json_files[@]} dashboard(s) in $(basename "$DASHBOARD_DIR")/"

# ── Generate ConfigMap with embedded dashboards ──────────────────
{
cat <<'HEADER'
---
# AUTO-GENERATED: Grafana Provisioning ConfigMaps
# Generated by: scripts/generate-grafana-provisioning.sh
# This ConfigMap provides dashboards for automatic provisioning
# Regenerate with: ./scripts/generate-grafana-provisioning.sh

HEADER

cat <<EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: $NAMESPACE
  labels:
    app: grafana
data:
EOF

for f in "${json_files[@]}"; do
  name="$(basename "$f")"
  echo "  $name: |"
  # Indent every line of the JSON by 4 spaces for YAML embedding
  sed 's/^/    /' "$f"
  echo ""
  echo "  Adding: $name" >&2
done

# ── Append the dashboard-provider ConfigMap ──────────────────────
cat <<EOF

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provider
  namespace: $NAMESPACE
  labels:
    app: grafana
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'smart-city-ids'
        orgId: 1
        folder: 'Smart City IDS'
        type: file
        disableDeletion: false
        editable: true
        updateIntervalSeconds: 10
        options:
          path: /var/lib/grafana/dashboards
EOF

} > "$OUTPUT"

lines=$(wc -l < "$OUTPUT")
echo ""
echo "Wrote $OUTPUT ($lines lines)"
echo "Apply with:  kubectl apply -f $OUTPUT -n $NAMESPACE"
