#!/bin/bash
# =============================================================================
# Smart City IDS - Grafana Provisioning Generator
# Generates ConfigMaps from dashboard JSON files
# Usage: bash scripts/generate-grafana-provisioning.sh [--output FILE] [--help]
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")}" && pwd)"
source "$SCRIPT_DIR/lib/script-utils.sh"

init_script "$0" "Grafana Provisioning Generator"

REPO_ROOT=$(dirname "$SCRIPT_DIR")
DASHBOARDS_DIR="$REPO_ROOT/infrastructure/monitoring"
OUTPUT_FILE="${REPO_ROOT}/k8s-manifests/grafana-provisioning-dashboards.yaml"

while [[ $# -gt 0 ]]; do
    case $1 in
        --output)  OUTPUT_FILE="$2"; shift 2 ;;
        --help)    print_help "generate-grafana-provisioning.sh [--output FILE]"; exit 0 ;;
        *)         die "Unknown option: $1" ;;
    esac
done

ensure_command jq

log_section "CONFIGURATION"
log_info "Dashboards Directory: $DASHBOARDS_DIR"
log_info "Output File: $OUTPUT_FILE"
echo ""

if [[ ! -d "$DASHBOARDS_DIR" ]]; then
    die "Dashboards directory not found: $DASHBOARDS_DIR"
fi

log_section "GENERATING PROVISIONING"

mkdir -p "$(dirname "$OUTPUT_FILE")"

# Generate ConfigMaps
log_info "Scanning for dashboard files..."
DASHBOARD_COUNT=$(find "$DASHBOARDS_DIR" -name "*.json" 2>/dev/null | wc -l)
log_info "Found: $DASHBOARD_COUNT dashboard files"
echo ""

# Create provisioning YAML
{
    cat << 'EOF'
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provisioning
  namespace: monitoring
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'Smart City IDS'
      orgId: 1
      type: file
      disableDeletion: false
      options:
        path: /var/lib/grafana/dashboards

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-generated
  namespace: monitoring
data:
EOF
    
    find "$DASHBOARDS_DIR" -name "*.json" -type f | while read -r dashboard; do
        name=$(basename "$dashboard" .json)
        echo "  ${name}.json: |"
        jq . "$dashboard" | sed 's/^/    /'
    done
} > "$OUTPUT_FILE"

log_info "✓ ConfigMap generated: $OUTPUT_FILE"
log_info "Dashboards embedded: $DASHBOARD_COUNT"
echo ""
log_section "NEXT STEPS"
echo "kubectl apply -f $OUTPUT_FILE"
echo ""
fi

# Find all dashboard JSON files
DASHBOARD_FILES=($(find "$DASHBOARDS_DIR" -maxdepth 1 -name "grafana-dashboard-*.json" -type f | sort))

if [ ${#DASHBOARD_FILES[@]} -eq 0 ]; then
    echo "❌ Error: No dashboard files found matching grafana-dashboard-*.json"
    exit 1
fi

echo "📊 Found ${#DASHBOARD_FILES[@]} dashboard(s):"
for file in "${DASHBOARD_FILES[@]}"; do
    echo "   - $(basename "$file")"
done

# Create the ConfigMap YAML
cat > "$OUTPUT_FILE" << 'EOF'
---
# AUTO-GENERATED: Grafana Provisioning ConfigMaps
# Generated by: scripts/generate-grafana-provisioning.sh
# This ConfigMap provides dashboards for automatic provisioning
# Regenerate with: ./scripts/generate-grafana-provisioning.sh

apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: monitoring
  labels:
    app: grafana
data:
EOF

# Add each dashboard file to ConfigMap
for file in "${DASHBOARD_FILES[@]}"; do
    filename=$(basename "$file")
    key="${filename%.json}"  # Remove .json extension
    
    echo "   Adding: $filename"
    
    # Add the file content with proper YAML indentation
    # For JSON content in ConfigMap, we need to preserve formatting
    cat >> "$OUTPUT_FILE" << EOF2
  $key.json: |
EOF2
    
    # Indent the JSON file content by 4 spaces for ConfigMap data
    sed 's/^/    /' "$file" >> "$OUTPUT_FILE"
    
    echo "" >> "$OUTPUT_FILE"  # Add blank line between files
done

# Also create/update the provisioning config
cat >> "$OUTPUT_FILE" << 'EOF'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provider
  namespace: monitoring
  labels:
    app: grafana
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'smart-city-ids'
        orgId: 1
        folder: 'Smart City IDS'
        type: file
        disableDeletion: false
        editable: true
        updateIntervalSeconds: 10
        options:
          path: /var/lib/grafana/dashboards
EOF

echo ""
echo "✅ ConfigMap generated: $OUTPUT_FILE"
echo ""
echo "📋 Next steps:"
echo "   1. Review the generated file: cat $OUTPUT_FILE"
echo "   2. Apply to cluster: kubectl apply -f $OUTPUT_FILE"
echo "   3. Update Grafana deployment volume: kubectl patch deployment grafana -n monitoring --patch-file - << 'PATCH'"
echo "      spec:"
echo "        template:"
echo "          spec:"
echo "            volumes:"
echo "            - name: dashboards"
echo "              configMap:"
echo "                name: grafana-dashboards"
echo "            - name: dashboards-provisioning"
echo "              configMap:"
echo "                name: grafana-dashboard-provider"
echo "      PATCH"
echo ""
echo "ℹ️  Grafana will automatically load dashboards on next pod restart."
echo "    No load-dashboards.sh script needed!"
