#!/bin/bash

###############################################################################
# generate-grafana-provisioning.sh
# 
# Generates Grafana provisioning ConfigMaps from dashboard files.
# This script embeds all dashboard JSON files from infrastructure/monitoring/
# into Kubernetes ConfigMaps for automatic loading.
#
# Usage:
#   ./scripts/generate-grafana-provisioning.sh
#   kubectl apply -f k8s-manifests/grafana-provisioning-generated.yaml
#
###############################################################################

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
DASHBOARDS_DIR="$REPO_ROOT/infrastructure/monitoring"
OUTPUT_FILE="$REPO_ROOT/k8s-manifests/grafana-provisioning-dashboards.yaml"

echo "🔧 Generating Grafana provisioning ConfigMaps..."
echo "   Dashboards dir: $DASHBOARDS_DIR"
echo "   Output file: $OUTPUT_FILE"

# Check if dashboards directory exists
if [ ! -d "$DASHBOARDS_DIR" ]; then
    echo "❌ Error: Dashboards directory not found: $DASHBOARDS_DIR"
    exit 1
fi

# Find all dashboard JSON files
DASHBOARD_FILES=($(find "$DASHBOARDS_DIR" -maxdepth 1 -name "grafana-dashboard-*.json" -type f | sort))

if [ ${#DASHBOARD_FILES[@]} -eq 0 ]; then
    echo "❌ Error: No dashboard files found matching grafana-dashboard-*.json"
    exit 1
fi

echo "📊 Found ${#DASHBOARD_FILES[@]} dashboard(s):"
for file in "${DASHBOARD_FILES[@]}"; do
    echo "   - $(basename "$file")"
done

# Create the ConfigMap YAML
cat > "$OUTPUT_FILE" << 'EOF'
---
# AUTO-GENERATED: Grafana Provisioning ConfigMaps
# Generated by: scripts/generate-grafana-provisioning.sh
# This ConfigMap provides dashboards for automatic provisioning
# Regenerate with: ./scripts/generate-grafana-provisioning.sh

apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: monitoring
  labels:
    app: grafana
data:
EOF

# Add each dashboard file to ConfigMap
for file in "${DASHBOARD_FILES[@]}"; do
    filename=$(basename "$file")
    key="${filename%.json}"  # Remove .json extension
    
    echo "   Adding: $filename"
    
    # Add the file content with proper YAML indentation
    # For JSON content in ConfigMap, we need to preserve formatting
    cat >> "$OUTPUT_FILE" << EOF2
  $key.json: |
EOF2
    
    # Indent the JSON file content by 4 spaces for ConfigMap data
    sed 's/^/    /' "$file" >> "$OUTPUT_FILE"
    
    echo "" >> "$OUTPUT_FILE"  # Add blank line between files
done

# Also create/update the provisioning config
cat >> "$OUTPUT_FILE" << 'EOF'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provider
  namespace: monitoring
  labels:
    app: grafana
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: 'smart-city-ids'
        orgId: 1
        folder: 'Smart City IDS'
        type: file
        disableDeletion: false
        editable: true
        updateIntervalSeconds: 10
        options:
          path: /var/lib/grafana/dashboards
EOF

echo ""
echo "✅ ConfigMap generated: $OUTPUT_FILE"
echo ""
echo "📋 Next steps:"
echo "   1. Review the generated file: cat $OUTPUT_FILE"
echo "   2. Apply to cluster: kubectl apply -f $OUTPUT_FILE"
echo "   3. Update Grafana deployment volume: kubectl patch deployment grafana -n monitoring --patch-file - << 'PATCH'"
echo "      spec:"
echo "        template:"
echo "          spec:"
echo "            volumes:"
echo "            - name: dashboards"
echo "              configMap:"
echo "                name: grafana-dashboards"
echo "            - name: dashboards-provisioning"
echo "              configMap:"
echo "                name: grafana-dashboard-provider"
echo "      PATCH"
echo ""
echo "ℹ️  Grafana will automatically load dashboards on next pod restart."
echo "    No load-dashboards.sh script needed!"
