apiVersion: v1
kind: Service
metadata:
  name: ids-api
  namespace: smart-city
  labels:
    app: ids-api
spec:
  selector:
    app: ids-api
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ids-api
  namespace: smart-city
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: ids-api
  namespaceSelector:
    matchNames:
      - smart-city
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scheme: http
